use_frameworks!

platform :ios, '8.0'

target 'HBTableViewFrameWork_Example' do
  pod 'HBTableViewFrameWork', :path => '../'

  target 'HBTableViewFrameWork_Tests' do
    inherit! :search_paths

    
  end
end
